# The URL the site will be built for
base_url = "https://blag.cedeela.fr"

title = "The Blag — Logic And Graphics"

# math support
#katex_enable = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false


# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "en"

generate_rss = true
generate_feed = true
feed_filename = "rss.xml"

# submodule https://github.com/getzola/hyde into `themes/` dir
#theme = "hyde"
theme = "even"

taxonomies = [
#    # You can enable/disable RSS
    {name = "authors", rss = false},
    {name = "tags", rss = true},
]

[extra]
# Put all your custom variables here

# side
#hyde_links = [
even_menu = [
    {url = "/", name = "Home"},
    {url = "/rss.xml", name = "RSS feed"},
    #{url = "/categories", name = "Categories"},
    {url = "/tags", name = "Tags"},
    #{url = "/authors", name = "Authors"},
    {url = "https://github.com/c-cube", name = "Simon's github"},
    {url = "https://github.com/vbarrielle", name = "Shuba's github"},
]

even_title = "The Blag: Logic And Graphics"

# TODO mathjax: https://github.com/getzola/zola/issues/442

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
#highlight_theme = "css"
highlight_theme = "base16-ocean-dark"
